---
path: github.com/mikunalpha/mog/api
deps:
  - loc: gopkg.in/gin-gonic/gin.v1
    type: goget

  - loc: gopkg.in/mgo.v2
    type: goget
  
  - loc: https://github.com/dgrijalva/jwt-go.git
    type: git
    reference: master
    path: github.com/dgrijalva/jwt-go

  - loc: https://github.com/jinzhu/gorm.git
    type: git
    reference: master
    path: github.com/jinzhu/gorm
  
  - loc: https://github.com/jinzhu/inflection.git
    type: git
    reference: master
    path: github.com/jinzhu/inflection
  
  - loc: https://github.com/PuerkitoBio/goquery.git
    type: git
    reference: master
    path: github.com/PuerkitoBio/goquery
